### ISSUE TITLE
Support XADD MAXLEN

### ISSUE THREAD

**Issue by zeejers** [tamimaj/nestjs-redis-streams#23]
The lib does not currently support MAXLEN, which is crucial in making sure that you don't experience an out of memory error if you aren't using the deleteAfterAck option when working with large streams.

We ran into this issue in our testing, and found others may gain from the change. See the note on "Capped Streams" here: https://redis.io/docs/latest/commands/xadd

**Comment by tamimaj** [comment]
@zeejers Thanks for the improvements. Merged in v1.3.0.
