### ISSUE TITLE
What does block option mean?

### ISSUE THREAD

**Issue by salos1982** [tamimaj/nestjs-redis-streams#6]
Hi, in the documentation there is code
```
streams: {
        block: 5000,
        consumer: 'users-1',
        consumerGroup: 'users',
      },
```
What does block: 5000 mean?

**Comment by tamimaj** [comment]
Hi @salos1982, 
This is a parameter from Redis Streams in the [XREADGROUP](https://redis.io/commands/xreadgroup/) to timeout after certain milliseconds to off-load the network. So the listener is an infinite loop trying to read from the Redis server and will timeout after 5000 milliseconds, which means if no streams were pushed before the 5000 finishes, it will timeout with null (found nothing) and then will try to listen again. If the block is larger the listener will be awaiting longer, EG. 10 seconds before he comes back with null.

**Comment by salos1982** [comment]
Thanks for reply
