### ISSUE TITLE
Could not async register ClientsModule

### ISSUE THREAD

**Issue by salos1982** [tamimaj/nestjs-redis-streams#7]
Hi,

I have the following code:
```
RedisStreamClientModule.registerAsync({
      useFactory: (config: ConfigService) => {
        return config.redisStreamsConfig; // config is undefined
      },
      inject: [ConfigService],
      imports: [ConfigModule.register()],
    }),
```
And I get that config is not injected into useFactory

**Comment by tamimaj** [comment]
Check if this way you still getting undefined:

```ts
@Module({
  imports: [
    ConfigModule.forRoot({
      isGlobal: true,
    }),
    RedisStreamClientModule.registerAsync({
      useFactory: (config: ConfigService) => {
        return config.redisStreamsConfig; // config should be injected correctly here
      },
      inject: [ConfigService],
    }),
  ],
})
export class MyModule {}
```

Also, [try to pass the params directly ](https://github.com/tamimaj/nestjs-redis-streams#async-registerasync--forrootasync)and check that lib is working fine to make sure the issue relies on the ConfigModule and not the lib implementation.

**Comment by salos1982** [comment]
```
ConfigModule.forRoot({
      isGlobal: true,
    }),
```
Does not exist in my code. ConfigModule is my module, so there are no additional functions.
Config service works fine. This is the code that works with redis
```
ClientsModule.registerAsync([
      {
        name: REDIS_CONFIG,
        useFactory: (config: ConfigService) => {
          return config.redisConfig;
        },
        inject: [ConfigService],
        imports: [ConfigModule.register()],
      },
    ])
```

I think the reason is that `ConfigModule.register()` returns `Promise<DynamicModule>`

**Comment by tamimaj** [comment]
Sorry @salos1982 I don't get this part 
> Does not exist in my code. ConfigModule is my module, so there are no additional functions. 

Have you initialized the config module like this? **https://docs.nestjs.com/techniques/configuration**

**Comment by tamimaj** [comment]
@salos1982 The issue was fixed. Thanks for reporting.
