### ISSUE TITLE
ConfigService = undefined on async registration of client module

### ISSUE THREAD

**Issue by level55** [tamimaj/nestjs-redis-streams#8]
Hello,
I tried to use your redis-client module, but I encountered a problem where the 'configService' passed to `useFactory` of client module is `undefined` when I run the app.

![image](https://github.com/tamimaj/nestjs-redis-streams/assets/17147147/78576b21-5261-41c4-8722-b49a2152d015)

So this issue looks similar to https://github.com/tamimaj/nestjs-redis-streams/issues/7.

To reproduce the problem I used your client app example and modified it a little:
https://github.com/level55/redis-streams-client-app
(see `app.module.ts`)

On application start (`yarn start`) you'll see the following error:
```
[Nest] 76319  - 10/17/2023, 12:07:47 AM   
ERROR [ExceptionHandler] Cannot read properties of undefined (reading 'get')
TypeError: Cannot read properties of undefined (reading 'get')".
```

Could you please check this? Perhaps I'm missing something?

Thank you in advance and please let me know if you need any more details.

**Comment by tamimaj** [comment]
Hey @level55 Thanks for reporting this. I will debug it ASAP and see what's going on. Will post again once I come up with something.

**Comment by tamimaj** [comment]
@level55 The issue is fixed. Thank you very much for reporting.

**Comment by noveo-vitaliy** [comment]
@tamimaj, Thank you very much for the quick fix and for your work on this library in general :)

**Comment by level55** [comment]
@tamimaj, Thank you very much for the quick fix and for your work on this library in general :)
